import type { ComponentProps } from 'react';
import type { ClerkProvider } from '@clerk/react';

// Textos de Clerk en español rioplatense, con el mismo voseo que el resto de 404Bank.
// Sin dependencia extra: lo que no esté acá cae al inglés por defecto de Clerk.
type Localizacion = NonNullable<ComponentProps<typeof ClerkProvider>['localization']>;

export const clerkLocalizacion: Localizacion = {
  locale: 'es-AR',
  dividerText: 'o',
  socialButtonsBlockButton: 'Continuar con {{provider|titleize}}',
  formFieldLabel__emailAddress: 'Email',
  formFieldLabel__username: 'Nombre de usuario',
  formFieldLabel__emailAddress_username: 'Email o nombre de usuario',
  formFieldLabel__password: 'Contraseña',
  formFieldLabel__confirmPassword: 'Repetí la contraseña',
  formFieldLabel__firstName: 'Nombre',
  formFieldLabel__lastName: 'Apellido',
  formFieldLabel__phoneNumber: 'Teléfono',
  formFieldInputPlaceholder__emailAddress: 'tu@email.com',
  formFieldInputPlaceholder__username: 'Tu nombre de usuario',
  formFieldInputPlaceholder__emailAddress_username: 'Tu email o usuario',
  formFieldInputPlaceholder__password: 'Tu contraseña',
  formFieldInputPlaceholder__signUpPassword: 'Mínimo 8 caracteres',
  formFieldAction__forgotPassword: '¿Te olvidaste la contraseña?',
  formFieldHintText__optional: 'Opcional',
  formFieldError__notMatchingPasswords: 'Las contraseñas no coinciden.',
  formFieldError__matchingPasswords: 'Las contraseñas coinciden.',
  formButtonPrimary: 'Continuar',
  formButtonPrimary__verify: 'Verificar',
  backButton: 'Volver',
  footerActionLink__useAnotherMethod: 'Usar otro método',
  signInEnterPasswordTitle: 'Ingresá tu contraseña',
  signUp: {
    start: {
      title: 'Creá tu usuario',
      subtitle: 'Para seguir con 404Bank',
      actionText: '¿Ya tenés cuenta?',
      actionLink: 'Ingresá',
    },
    continue: {
      title: 'Completá los datos que faltan',
      subtitle: 'Para seguir con 404Bank',
      actionText: '¿Ya tenés cuenta?',
      actionLink: 'Ingresá',
    },
    emailCode: {
      title: 'Revisá tu email',
      subtitle: 'Para seguir con 404Bank',
      formTitle: 'Código de verificación',
      formSubtitle: 'Escribí el código que te mandamos a tu email',
      resendButton: '¿No te llegó? Reenviar',
    },
    emailLink: {
      title: 'Revisá tu email',
      subtitle: 'Para seguir con 404Bank',
      formTitle: 'Link de verificación',
      formSubtitle: 'Usá el link que te mandamos a tu email',
      resendButton: '¿No te llegó? Reenviar',
    },
  },
  signIn: {
    start: {
      title: 'Ingresá a 404Bank',
      subtitle: 'Qué bueno verte de nuevo',
      actionText: '¿Todavía no tenés cuenta?',
      actionLink: 'Abrí tu cuenta',
      actionLink__use_email: 'Usar email',
      actionLink__use_username: 'Usar nombre de usuario',
      actionLink__use_email_username: 'Usar email o usuario',
    },
    password: {
      title: 'Ingresá tu contraseña',
      subtitle: 'Para seguir con 404Bank',
      actionLink: 'Usar otro método',
    },
    forgotPasswordAlternativeMethods: {
      title: '¿Te olvidaste la contraseña?',
      label__alternativeMethods: 'O ingresá con otro método',
      blockButton__resetPassword: 'Restablecer la contraseña',
    },
    forgotPassword: {
      title: 'Restablecer la contraseña',
      subtitle: 'para restablecer tu contraseña',
      subtitle_email: 'Primero, escribí el código que te mandamos a tu email',
      formTitle: 'Código para restablecer',
      resendButton: '¿No te llegó? Reenviar',
    },
    resetPassword: {
      title: 'Elegí una contraseña nueva',
      formButtonPrimary: 'Restablecer contraseña',
      successMessage: 'Listo, cambiaste tu contraseña. Te estamos ingresando…',
      requiredMessage: 'Por seguridad, tenés que cambiar tu contraseña.',
    },
    emailCode: {
      title: 'Revisá tu email',
      subtitle: 'Para seguir con 404Bank',
      formTitle: 'Código de verificación',
      resendButton: '¿No te llegó? Reenviar',
    },
  },
  unstable__errors: {
    form_identifier_not_found: 'No encontramos una cuenta con ese dato. Revisalo o abrí una cuenta nueva.',
    form_password_incorrect: 'La contraseña no es correcta. Probá de nuevo.',
    form_password_or_identifier_incorrect: 'El email o la contraseña no son correctos. Probá de nuevo.',
    form_code_incorrect: 'El código no es correcto. Revisalo y probá de nuevo.',
    form_identifier_exists__email_address: 'Ese email ya tiene una cuenta. Probá ingresar.',
    form_identifier_exists__username: 'Ese nombre de usuario ya está en uso. Elegí otro.',
    form_param_format_invalid__email_address: 'Escribí un email válido, por ejemplo tu@email.com.',
    form_password_length_too_short: 'La contraseña es muy corta.',
    form_password_pwned: 'Esa contraseña apareció en una filtración de datos. Elegí otra.',
    form_password_pwned__sign_in: 'Esa contraseña apareció en una filtración de datos. Restablecela para seguir.',
    form_password_not_strong_enough: 'La contraseña es muy débil. Sumale largo o variedad.',
    form_username_invalid_length: 'El nombre de usuario tiene que tener entre 4 y 64 caracteres.',
    form_username_invalid_character: 'El nombre de usuario solo puede tener letras, números, guiones y guiones bajos.',
    form_param_nil: 'Completá este campo.',
    captcha_invalid: 'No pudimos verificar que seas una persona. Recargá la página e intentá de nuevo.',
    passwordComplexity: {
      sentencePrefix: 'Tu contraseña tiene que tener',
      minimumLength: '{{length}} caracteres o más',
      maximumLength: 'menos de {{length}} caracteres',
      requireNumbers: 'un número',
      requireLowercase: 'una minúscula',
      requireUppercase: 'una mayúscula',
      requireSpecialCharacter: 'un carácter especial',
    },
    zxcvbn: {
      notEnough: 'La contraseña es muy débil.',
      couldBeStronger: 'Sirve, pero podría ser más fuerte. Sumale caracteres.',
      goodPassword: 'Buena contraseña.',
    },
  },
};
